name: Sync with Original Repo

on:
  schedule:
    - cron: '0 0 * * *' 
  push:
    branches:
      - master 

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Alternate Repo
      uses: actions/checkout@v3

    - name: Add Original Repo as Remote
      run: git remote add upstream https://github.com/Blueion76/FCAUconnect-HA.git

    - name: Fetch Changes from Original Repo
      run: git fetch upstream

    - name: Merge Changes from Original Repo
      run: git merge upstream/main --allow-unrelated-histories -m "Sync from original repo"

    - name: Push Changes
      run: git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
